### ISSUE TITLE
Does it work with ios17 beta?

### ISSUE THREAD

**Issue by f-exuan21** [yoxisem544/ScreenshotPreventing-iOS#14]
Does it work with ios17 beta?
For me, it doesn't work...

**Comment by aerialkoala** [comment]
> Does it work with ios17 beta? For me, it doesn't work...

Did you solve it on iOS17

**Comment by f-exuan21** [comment]
> > Does it work with ios17 beta? For me, it doesn't work...
> 
> Did you solve it on iOS17

Yes I did. 
But I didn't use this code. :(

**Comment by aerialkoala** [comment]
> > > Does it work with ios17 beta? For me, it doesn't work...
> > 
> > 
> > Did you solve it on iOS17
>  
> Yes I did. But I didn't use this code. :(

could you show me your code? you know why it doesn't work

**Comment by f-exuan21** [comment]
> > > > Does it work with ios17 beta? For me, it doesn't work...
> > > 
> > > 
> > > Did you solve it on iOS17
> >  
> > Yes I did. But I didn't use this code. :(
> 
> could you show me your code? you know why it doesn't work

Sure. I'll show you before tomorrow.

**Comment by f-exuan21** [comment]
> > > > Does it work with ios17 beta? For me, it doesn't work...
> > > 
> > > 
> > > Did you solve it on iOS17
> > 
> > 
> > Yes I did. But I didn't use this code. :(
> 
> could you show me your code? you know why it doesn't work

```
extension UIView {

    func blockScreenShot() {
        DispatchQueue.main.asyc {
            let field = UITextField()
            field.isSecureTextEntry = true
            field.isUserInteractionEnabled = false

            self.addSubview(field)
            field.centerYAnchor.constraint(equalTo: self.centerYAnchor).isActive = true
            field.centerXAnchor.constraint(equalTo: self.centerXAnchor).isActive = true

            field.layer.removeFromSuperlayer()
            self.layer.superlayer?.insertSublayer(field.layer, at: 0)
            field.layer.sublayers?.last?.addSublayer(self.layer)
        }
    }

}
```

You can use it for the view you want to block the screenshot.
For example, i applied the code to window's view.

```
self.window?.blockScreenShot()
```

* This code might be able to contain typos.

**Comment by swarajsinghdev** [comment]
@f-exuan21 i am unable to use i tried to use this in viewdidload

**Comment by JayantBadlani** [comment]
@aerialkoala @f-exuan21 [ScreenShield](https://github.com/JayantBadlani/ScreenShield) is a similar library that provides a simple way to protect your app's content from being captured or recorded by screenshots and screen recordings, supported in iOS 17 as well.
[ScreenShield](https://github.com/JayantBadlani/ScreenShield)

**Comment by f-exuan21** [comment]
> @f-exuan21 i am unable to use i tried to use this in viewdidload 

If you don't set the correct Autolayout, it won't work well. I recommend you check that part.

**Comment by malt-blue-gen** [comment]
> > > Does it work with ios17 beta? For me, it doesn't work...
> > 
> > Did you solve it on iOS17
> 
> Yes I did. 
> But I didn't use this code. :(

What did you use then??

**Comment by JayantBadlani** [comment]
@yoxisem544, @malt-blue-gen you can try [ScreenShield](https://github.com/JayantBadlani/ScreenShield), it's updated and support iOS17
