### ISSUE TITLE
Not working on iOS 13

### ISSUE THREAD

**Issue by viktorkiver** [yoxisem544/ScreenshotPreventing-iOS#4]

**Comment by amitkumar3968** [comment]
for ios 13, you can use below snippet(Objc) to run in ios 13, 

 CGRect frame=CGRectMake(0, 40, 300, 60);
    UITextField * testView = [[UITextField alloc]initWithFrame:frame];
    testView.backgroundColor = [UIColor clearColor];
    testView.secureTextEntry = true;
    testView.tag = 9090;
    [ self.view addSubview:testView];

  for(UIView *theview in testView.subviews){
        NSLog(@"theview - %@", theview.description);
       }

and paste the resulted view name in 
https://github.com/yoxisem544/ScreenshotPreventing-iOS/blob/79e135bec19c5a894db716849e721f2f3c50d40c/Sources/ScreenshotPreventing/HiddenContainerRecognizer.swift#L32

 this method with proper condition of ios 13 availability.

**Comment by yoxisem544** [comment]
Fixed in version 1.2.2. Please try it out.
