### ISSUE TITLE
Lock view in iPhone SE

### ISSUE THREAD

**Issue by MaatheusGois** [yoxisem544/ScreenshotPreventing-iOS#7]

**Comment by YaroslavReznichenko** [comment]
Yes, I found this bug.

Need to add this line 

container.isUserInteractionEnabled = true -> line 82

in next code
<img width="811" alt="Знімок екрана 2023-04-27 о 12 35 58" src="https://user-images.githubusercontent.com/131962448/234824805-0536f747-4019-4402-b5c8-252b0c34090f.png">

**Comment by yoxisem544** [comment]
Can you provide more information on how to reproduce this bug?

**Comment by YaroslavReznichenko** [comment]
I reproduced it on simulator Iphone 11 or else does not matter but IOS 15.0 When IOS 16.2 for example everything is ok. I have table view which I need to hide from screenshots. So when I launch simulator with IOS 15.0 table view does not scrolling. I tried to add this line in your code and bug was fixed.

**Comment by yoxisem544** [comment]
Did you use this view inside table view's cell?

**Comment by YaroslavReznichenko** [comment]
No, I put whole table)
<img width="409" alt="Знімок екрана 2023-04-27 о 17 57 38" src="https://user-images.githubusercontent.com/131962448/234903055-bac97058-9c5f-4ea0-b4f0-8baf5548d8a1.png">

Also I have another view with gestures. Same problem -> no user interactionenabled

**Comment by yoxisem544** [comment]
I think the problem is TextView's hidden container will takeover every touch event. So non of these touch events will be passed through responder chain. I will try to fix it, thank you for the information.

**Comment by YaroslavReznichenko** [comment]
Thanks) Let me know when I can test it in my project please) And thank you for this framework!

**Comment by yoxisem544** [comment]
Fixed in version 1.2.2. Please try it out.

**Comment by YaroslavReznichenko** [comment]
Works well) Thanks
